name: Deploy master to EBS
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Use the Go version from go.mod
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./... -count=1

    - run: GOOS=linux GOARCH=arm64 go build .

    - name: Generate deployment package
      run: zip -r ${{github.SHA}}.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_CI_CD_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_CI_CD_SECRET_ACCESS_KEY }}
        application_name: Bible-API-14-5-2025
        environment_name: Bible-API-14-5-2025-env
        version_label: Version_${{github.SHA}}
        region: us-west-2
        deployment_package: ${{github.SHA}}.zip
